### ISSUE TITLE
A Trouble with Date Picker

### ISSUE THREAD

**Issue by Hayko1994** [creativetimofficial/now-ui-kit#16]
Hi. I am trying to integrate date picker from this material kit into my project. It seems I've copied all needed snippets while it doesn't work. Can you help me to solve the problem? I am using Bootstrap 4 and here is the link on code pen: 
[https://codepen.io/Hayko/pen/QgvYMv ](url)

**Comment by arpit016** [comment]
**@Hayko1994**  I checked your link on codepen and the issue is that you have not copied the whole nowuikit css code and have only used the css code for datepicker. Copy the whole nowuikit CSS and then run, it will work fine. After you do that then open the developer tools and check that it's not just the datepicker code inside the css which is being used to produce the datepicker table, other classes are also responsible for it to appear. Few classes css code are required such as **.open**, **.dropdown-menu**, **.dropdown-menu .open**, **form-control**, etc. So, copying only the datepicker css code won't be enough.

**Comment by Hayko1994** [comment]
It seems a bit confusing.  After copying all it will take a lot of time to remove all parts which are not used. Is there any demo for just date picker?  I found an example of date picker on the site but it was old. So for Bootstrap 4, only this mode will work perfectly.

**Comment by alexandru-paduraru** [comment]
@Hayko1994 we just added a detailed explanation with the current stages of dev and the difference between the BS 3 and 4 datepickers and products here: https://www.creative-tim.com/product/now-ui-kit#comment-3608

We will see what we can do with the plugin from Material Kit PRO. What we know now is that it didn't work on BS4 and that's why we didn't use it.

**Comment by alexandru-paduraru** [comment]
You can also use the design of the datepicker from the SASS files, don't have to remove anything from CSS, just remove the imports from SASS. assets/sass/now-ui-kit/plugins/_plugin-datepicker.scss. More about SASS here: http://sass-lang.com/

**Comment by Hayko1994** [comment]
Which files do I need to use from sass? I've copied only date picker.scss from plugins folder also date picker mixins but it shows error on 13th line as undefined.

**Comment by alexandru-paduraru** [comment]
@Hayko1994 variables and mixins. Basically, anything that is before plugin-datepicker, without the other plugins if you don't use them.
