### ISSUE TITLE
Any way to have the normal "drop down" nav on mobile?

### ISSUE THREAD

**Issue by dylanm21** [creativetimofficial/now-ui-kit#23]
I have everything set up correctly but the ui kit nav loads very weird on mobile.

Here is an example, i cant explain what it's doing.

http://flashmanwade.co

I did the responsive.scss sass and complied. still acting weird

**Comment by dragosct10** [comment]
Hi @dylanm21! To fix the problem with the navbar, you have to remove the `id="mydropdown"` because this `id` from the `div` with class `.navbar-collapse` is activating the bootstrap javascript for the default navbar-collapse which in our case we don't need this. Please let us know if everything is working fine! 

Regards,
Dragos

**Comment by dylanm21** [comment]
Hey! I tried that, it looks like the animation is working, but the content is blank where the nav should show the bottons. any ideas?

**Comment by dylanm21** [comment]
nvm got it. thanks :)
