### ISSUE TITLE
Homepage white space on right side mobile

### ISSUE THREAD

**Issue by nmarriotti** [creativetimofficial/now-ui-kit#5]
Swiping the homepage to the left shows a huge empty white space on the right side.

Fixed by adding:

`html, body {
    width: 100%;
    height: 100%;
    margin: 0px;
    padding: 0px;
    overflow-x: hidden;  }`

![image1](https://cloud.githubusercontent.com/assets/16280179/26538730/57f17684-43fd-11e7-8333-a45997242832.PNG)

**Comment by alexandru-paduraru** [comment]
@nmarriotti the issue is coming from the 2 cols from Navigation Pills and Pagination. Please replace them with `.col-sm-6`

<img width="751" alt="screen shot 2017-05-29 at 10 26 18" src="https://cloud.githubusercontent.com/assets/2517758/26540284/4b189ac6-4459-11e7-95fa-748452471328.png">

Then everything will work fine.

Best,
Alex
